"""initial migration

Revision ID: 254b5fbcb6fa
Revises: 
Create Date: 2025-04-30 13:14:54.044519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254b5fbcb6fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.drop_constraint('project_templates_template_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'templates', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('project_templates_template_id_fkey', 'files', ['template_id'], ['id'])

    # ### end Alembic commands ###
